# Generated by Django 5.0.1 on 2024-01-14 19:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('cylinders', models.PositiveSmallIntegerField()),
                ('engine_type', models.CharField(max_length=100)),
                ('displacement', models.CharField(max_length=100)),
                ('displacement_type', models.CharField(choices=[('CI', 'Cubic Inches'), ('L', 'Liters')], max_length=2)),
                ('fuel_type', models.CharField(choices=[('GAS', 'Gas'), ('DIESEL', 'Diesel'), ('ELECTRIC', 'Electric'), ('HYBRID', 'Hybrid'), ('TWOSTROKE', 'Two Stroke Mix')], max_length=10)),
                ('description', models.CharField(max_length=1500)),
                ('color', models.CharField(max_length=100)),
                ('customizations', models.CharField(max_length=1000)),
                ('photos', django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='car_images/'), size=None)),
            ],
        ),
    ]
